### ISSUE TITLE
Annotation link click prevented propagation

### ISSUE THREAD

**Issue by yaoquan** [pisi/Reel#79] opened 2011-12-01 05:18 UTC
This happens in the development branch. What I'm trying to do here is to pop up some image onclick of a link annotation. However, clicking on a link annotation will cause the image to skip to the next scene. Either this should not happen or there could be some options to prevent the propagation of the click?

**Comment by pisi** [comment] 2011-12-01 18:08
Thanks for noticing! I did noticed too and the issue is fixed now, but not yet pushed to github. I'll push it online soon.

**Comment by pisi** [comment] 2011-12-04 16:17
Can you please verify it works as expected now. The patched code is in the [augmented-frames](/pisi/Reel/tree/augmented-frames) branch. Will merge it into development once verified. Thanks!

**Comment by pisi** [comment] 2011-12-17 23:26
@yaoquan I consider this bug as resolved. Please, verify the click on the annotation link no longer steps the rotation with the fresh [1.1.3-devel](/pisi/Reel/tree/development/). Thanks!

**Closed as completed** 2011-12-23 21:04 UTC
Labels: bug, resolved
