### ISSUE TITLE
Problem with frame count

### ISSUE THREAD

**Issue by gnatok** [pisi/Reel#201] opened 2013-06-11 15:08 UTC
Hi there.
I pulled today branches gh-190-image-change and gh-193 and found a bug. Number of frames does not counts properly.
Look at screenshoot. I have folder with 23 images and in settings i setup 23 frames but scroll goest to 31 frame. With master branch all OK.

![bug](https://f.cloud.github.com/assets/1182933/637650/b58e4cf6-d2a8-11e2-8d0c-fc0bf7e2b72c.png)

**Comment by pisi** [comment] 2013-06-11 18:29
Great catch! Thank you :)

**Comment by gnatok** [comment] 2013-06-12 08:07
@pisi how can i help you to fix this bug faster?

**Comment by pisi** [comment] 2013-06-12 11:14
Lengthen the day for me, please! :) No, seriously, a live example of this would help a lot.

**Comment by gnatok** [comment] 2013-06-12 11:31
@pisi here you are http://jsfiddle.net/fRCJs/

**Comment by pisi** [comment] 2013-06-12 11:43
Great! As I suspected. You are using version 1.2-devel, which may not always be 100% stable until it is actually released as next version. Since then some work have been done, so I replaced the one in the fiddle with the [latest development version](/pisi/Reel/tree/development) tagged for release as 1.2.2 and the issue is gone. http://jsfiddle.net/nysTw/1/

**Comment by gnatok** [comment] 2013-06-12 12:02
So now bug is closed i think. )) Works great. Thanks

**Closed as completed** 2013-06-12 12:08 UTC
Labels: support, resolved, verified

**Comment by pisi** [comment] 2013-06-12 22:31
My pleasure.

**Comment by pisi** [comment] 2013-11-05 14:59
Released today as part of [v1.3.0](/pisi/Reel/tree/v1.3.0)
