### ISSUE TITLE
problems with version update

### ISSUE THREAD

**Issue by al-ion** [pisi/Reel#121] opened 2012-05-02 10:30 UTC
Hello, i was using the bundle 1.2 and wanted to do an upgrade, but when i use the actual bundle (1.4.) then my page is not working anymore..

first i thought it is because of the new option "Suffix"  but setting Suffix:"" did not help..

My original working code:

<pre><code>

&lt;img id='id360' src='path/to/img/026.png' width="800px" height="450px" &#62;

<script>
    $('#id360').reel({
          frames:      99,
          frame:       20,
          speed:       0,
          brake:       1, 
          cw:           true,
          sequence:    'path/to/img/###.png'
        });
</script>

</code></pre>

what have changed? i had have searched in the wiki but still have no clue?..

**Comment by pisi** [comment] 2012-05-02 11:43
Actually what you did was downgrade. There's no version 1.4. There is 1.2 in the development (current release candidate [v1.2rc](/pisi/Reel/tree/v1.2rc)) and in the meantime some of its fixes were merged back into 1.1 (the current latest stable [v1.1.4](/pisi/Reel/tree/v1.1.4)).

The [CDN](/pisi/Reel/wiki/CDN) currently serves these bundles:

http://code.vostrel.cz/jquery.reel-bundle.js - 1.1.4
http://code.vostrel.cz/jquery.reel-edge-bundle.js - 1.2rc

You can also print out the precise version of Reel with `$.reel.version`.

**Comment by al-ion** [comment] 2012-05-02 11:54
sorry, the version that i was working with was:  Version: 1.1.3-devel

The version i wanted to try is:  Version: 1.1.4

My problem with the development version is that it contacts your server and i want to use it offline. The 1.1.4 didnt call home but is not working..

**Comment by pisi** [comment] 2012-05-02 12:11
It is like this: First, [1.1.3](/pisi/Reel/tree/v1.1.3) was released and the development version built upon it, hence 1.1.3-devel. The devel version will eventually become 1.2. When it reached stability, the it was released as [1.2beta](/pisi/Reel/tree/v1.2beta). Soon it became clear it would be beneficiary for the 1.1.x branch to gain some of these fixes to extend the time window for beta testing. So they were merged back into the branch and consequentially released as [1.1.4](/pisi/Reel/tree/v1.1.4) (as those changes didn't mean any API changes). And again, the current development version is based on the latest stable, hence [1.1.4-devel](/pisi/Reel/tree/development).

As the 1.1.4 contains only a fraction of changes, that went into 1.1.3-devel, it still is a downgrade. Sounds weird I know...

I'll advise you to go for the [1.1.4-devel](/pisi/Reel/tree/development) as that is the best what you can get right now.

**Comment by pisi** [comment] 2012-05-02 12:25
As for the "call home". Every Reel does that since 1.1 I think. The palm cursor isn't browser's own, it is a custom resource fetched from the [CDN](/pisi/Reel/wiki/CDN) Google-backed server I run to support all Reels worldwide.

In 1.1 this was an alternative only for browsers incapable of handling embedded base64 encoded images. But as the compatibility of cursors had been increased for 1.2, I had to switch from GIF to CUR file format, which is substantially bigger and not suitable for embedding into the code anymore. So in 1.2 cursors are fetched from CDN by default.

You can always set your own "home" with [`$.reel.cdn`](http://test.vostrel.cz/jquery.reel/docs/jquery.reel.html#Content-Delivery-Network) by doing (will apply globally to all Reels):

``` js
$.reel.cdn= "http://www.my-own-server-com/";
```

**Comment by al-ion** [comment] 2012-05-02 12:36
Hello, Thank you very much for your fast response!!!

i tried the 1.1.4-devel but it didnt worked either. Can you please explain how to provide the icon for an offline use without server?

**Comment by pisi** [comment] 2012-05-02 12:58
In 1.2 there is a new [`cursor`](http://test.vostrel.cz/jquery.reel/docs/jquery.reel.html#Customization) option, which accepts:
- either nothing (default), which results in `@CDN@jquery.reel.cur`
- or `"hand"`, which results in `@CDN@jquery.reel-drag.cur` and `@CDN@jquery.reel-drag-down.cur` (when dragged)
- or any CSS `cursor` declaration you wish

The `@CDN@` portion gets replaced with the value of `$.reel.cdn`. When you use your custom CSS declaration, the CDN is not prepended to it.

Get the cursor files from the CDN:
- http://code.vostrel.cz/jquery.reel.cur
- http://code.vostrel.cz/jquery.reel-drag.cur
- http://code.vostrel.cz/jquery.reel-drag-down.cur

**Comment by al-ion** [comment] 2012-05-06 03:47
Thanks for your Explanations.

I use the Reel for an offline showcase.

i still use the Version 1.1.3-devel, because it is the only version were the code i mentioned in my first post is working.

Now i did the cur files in the folder "img/" and tryed to add  $.reel.cdn = "img/" and but it is not working..

did you have any idea why?

**Comment by pisi** [comment] 2012-05-06 11:13
Have no idea. Please put up a jsfiddle to demostrate it not working. Thanks.

**Comment by al-ion** [comment] 2012-05-06 19:25
ok, here a demonstration on jsfiddle:
1. version 
   my code from above with the 1.1.3-devel reel.js
   is working
   http://jsfiddle.net/qgW65/1/
2. version
   my code with 1.1.4
   not working
   http://jsfiddle.net/qgW65/2/

**Comment by pisi** [comment] 2012-05-06 19:42
OK, I see now. The problem is with the `sequence` option. It is a new 1.2 feature, it doesn't exist in any 1.1.x version. Well it doesn't even exist in any development version anymore, because in the 1.2rc it was merged into existing `images` option as an alternative to the array this option can accept.

So if you'll use 1.2, you need to rename `sequence` to `images` and you're good to go. If 1.1.x, you will still need to use `images` and this time supply it a proper array.

Updated fiddle using 1.2rc (currently served edge version): http://jsfiddle.net/qgW65/3/
Fiddles are alwas helpful! :)

**Comment by al-ion** [comment] 2012-05-08 13:03
Thank you very much!! (For the Plugin AND the Help)

I tried to change do image(s) an it didnt work so i started the tread, maybe i just forgot the "s" at the end..

BTW i put  $.reel.cdn= "img/"; in the reel code on the beginning but it didnt worked, but when i changed it in the Plugin Code by Hand it works..

**Comment by pisi** [comment] 2012-05-08 14:03
Investigation of the CDN issue revealed a bug in it. Issue #124 has been created for this particular bug.

**Closed as completed** 2012-05-08 14:13 UTC
Labels: support, resolved
