### ISSUE TITLE
Negative speed no longer working in 1.3

### ISSUE THREAD

**Issue by shoany** [pisi/Reel#246] opened 2013-12-05 20:56 UTC
Hi there,
  I've been using 1.2 for a little while. In it, I'm allowed to, say, start an animation halfway through and use a negative speed to play it in reverse. In 1.3, however, negative speeds seem to be ignored and you can only play forwards (until it reaches the end of animation and autoreverses).

  I've also tried using the new reach event as a trigger (to, say, go from 15 out of 30 back to 1 out of 30) but it does the same thing, playing forwards to the end, rebounding and then finally reversing.

  Is there a new way to play in reverse?

Thanks!
Shawn

**Comment by pisi** [comment] 2013-12-05 23:19
Duplicate of #241.

Thanks for reporting. Looking into it...

**Closed as completed** 2013-12-05 23:19 UTC
Labels: duplicate

**Comment by pisi** [comment] 2013-12-17 19:10
#241 has been resolved and with it this issue too. You can join us in evaluation of fix if you can! :)
