### ISSUE TITLE
Issue with initial image when using individual images sequence.

### ISSUE THREAD

**Issue by bobbylee** [pisi/Reel#24] opened 2011-03-16 12:05 UTC
Hi there,
I just tried using the 'images' option to build the 360 view with individual images.

Here is an extract of my HTML:
<img id='imageReel' src='images/sequences/reel-01.jpg' width='427' height='640' />

Here is my jQuery code:
$(function(){
 $('#imageReel').reel({hint: 'test', path: 'images/sequences/', images: 
    [
       'reel-01.jpg',
       'reel-02.jpg',
       'reel-03.jpg',
       'reel-04.jpg'
     ]
   });
 });

For some reason, when the reel first loads, my original initial image gets replaced by some image meta data. Here is a result:

<img id="imageReel" src="data:image/gif;base64,R0lGODlhCAAIAIAAAAAAAAAAACH5BAEAAAAALAAAAAAIAAgAAAIHhI+py+1dAAA7" width="427" height="640" class="jquery-reel" style="display: block; width: 427px; height: 640px; ">

This only happens for individual images. I managed to find a way around by including the 'frame' option but it cannot be values 1,2 or 3 for some weird reason. So I'm using either frame:0 or frame:4 option to get the reel to work as it should.

I've also tried using the 'image' option but there were no difference. From the description I still don't quite understand what the 'image' option does.

It would be great to have a 360 view example for using individual images.

Lastly, the latest 1.1 improvements are very cool! 
Thanks for improving on this awesome plugin.

**Comment by bobbylee** [comment] 2011-03-16 12:08
Whoops! Like everyone else before me, I didn't see that this bug was already reported. My apologies.

**Comment by pisi** [comment] 2011-03-20 23:10
Exactly ;) For the record, it is a duplicate of [GH-11](https://github.com/pisi/Reel/issues/closed#issue/11) and I [just released](https://github.com/pisi/Reel/issues/closed#issue/11/comment/896575) the patch [version 1.1.1](https://github.com/pisi/Reel/tree/v1.1.1) with a cure for this pain.

**Closed as completed by pisi** 2011-03-20 23:10 UTC
Labels: bug, v1.1.1, duplicate
