### ISSUE TITLE
Specify autoplay rotations?

### ISSUE THREAD

**Issue by acicali** [pisi/Reel#182] opened 2013-03-21 21:28 UTC
A useful feature for me would be the ability to "autoplay" only a certain number of rotations.  For instance, a product might rotate once or twice automatically before stopping at its original position, after which the user would be able to freely rotate it.

Here's an example:
http://spritespin.ginie.eu/examples

**Comment by pisi** [comment] 2013-03-22 16:17
Hi,

this is a duplicate of #90, which is already resolved by adding a new `duration` option allowing to specify duration of animation in seconds. It currently sits on a [dedicated branch](/pisi/Reel/tree/gh-90-duration) awaiting version 1.3 (can not be released sooner due to API change..). Please grab the code from that branch, if you need that functionality right away (it is labeled 1.2, but it is 1.2.1 plus the duration feature).

**Closed as completed by pisi** 2013-03-22 16:17 UTC
Labels: duplicate
