### ISSUE TITLE
Image preloading in FireFox

### ISSUE THREAD

**Issue by MartinPluta** [pisi/Reel#231] opened 2013-09-22 12:44 UTC
Loading a sequence of 100 images with HD Resolution (1920px width and 1080px height), the reel does not display the images smoothly, but a flickering (reloading) is what can be experienced. I am using the reel for a scientific project. This does not appear in Internet Explorer, so this is probably related to image handling in FireFox?

Any comments or suggestions are welcome. Trying to find a fix for this.

Best regards

Martin

**Comment by pisi** [comment] 2013-09-23 11:41
Hi, yeah, Firefox is notoriously slow in updating fullscreen bitmaps, even when hardware accelerated. I have no cure for this yet other than recommendation of decreasing the visual complexity of the images and tinkering with compression and sizes, which may have positive effects on memory consumption.

When I am testing just loading & rendering time of an image in your dimensions with no Reel, no HTML nor Javascript, I am getting combined times of up to 89 ms for PNG with alpha, up to 43 ms for PNG without alpha channel. With default `tempo: 36` there's 27 ms window to load, which means that Firefox is not able to load such images in time.

I did the same test with JPG and the same dimensions loaded in no more than 21 ms on 100% quality and no more than 3 ms on 80% quality.

**So my general suggestion in these image dimensions would be to use JPGs with 80% or less compression quality.**

Duplicate of #196

**Closed as completed by pisi** 2013-09-23 11:41 UTC
Labels: duplicate
