### ISSUE TITLE
starting "frame" option does not work reliably with "images" array

### ISSUE THREAD

**Issue by pablosbrain** [pisi/Reel#19] opened 2011-03-03 16:05 UTC
When using an array of images with the "images" option, specifying the starting "frame" option does not work reliably. With or without the "frame" option, Reel doesn't seem to know what to use as a starting frame.  I'd prefer to just leave it blank but the image shows up blank/missing then to begin with until the user interacts with it enough to change the image.

**Comment by pisi** [comment] 2011-03-04 12:30
This is a duplicate of already resolved [issue 11](https://github.com/pisi/Reel/issues/closed#issue/11). Please see the solution there.

Sorry for any inconvenience.

**Closed as completed by pisi** 2011-03-04 12:30 UTC
Labels: bug, v1.1.1, duplicate

**Comment by pisi** [comment] 2011-03-20 23:12
For the record, I [just released](https://github.com/pisi/Reel/issues/closed#issue/11/comment/896575) the patch [version 1.1.1](https://github.com/pisi/Reel/tree/v1.1.1) with a cure for this pain.
