### ISSUE TITLE
Sticky top row bug in multi-row mode

### ISSUE THREAD

**Issue by otpfiste** [pisi/Reel#46] opened 2011-06-30 12:53 UTC
Nice new feature the multi-row possibility!
Follow me using your mini example:
when dragging the mini to the top (first row) the image locks there if you drag down vertically, only when dragging some steps horizontally it then jumps to the correct position.

Best Regards,
Oliver Pfister

**Comment by pisi** [comment] 2011-07-03 12:01
Thank you very much for reporting this issue. It has now been confirmed and a fix is scheduled for the next release.

**Comment by otpfiste** [comment] 2011-07-03 12:07
Ok, thanks a lot for your great work.

**Comment by pisi** [comment] 2011-09-30 10:10
Hey Oliver, I believe I have nailed it. It now passes the test for the issue and manual testing also seems to be in order. Can you please give it a try? Be sure to grab the patched code from the [development](/pisi/Reel/tree/development) brach. Thanks!

**Comment by otpfiste** [comment] 2011-09-30 18:51
Hi .pisi,
visual test works well with my 4 multi-row test images, thanks a lot!

**Comment by pisi** [comment] 2011-09-30 19:03
Awesome! :)

**Comment by otpfiste** [comment] 2012-02-28 16:36
Hi pisi, issue again present with new 1.1.4 release...

**Comment by pisi** [comment] 2012-02-28 18:06
The fix for this issue is still in [development](/pisi/Reel/tree/development) branch and hasn't been released yet as it is slated for the 1.2 release. That's why the 1.1.4 has the same issue as 1.1.3 did. I know, I should have included the fix into 1.1.4, but I missed it  - it's bad, but at least it's not worse. It will be fixed in 1.2. It is in the [1.2 beta](/pisi/Reel/tree/v1.2beta).

**Comment by otpfiste** [comment] 2012-02-28 18:54
On 28.02.2012 19:06, Petr Vostřel wrote:

> Again, dummy me... I just realized, that this issue's fix is part of the development branch and is slated as far as the 1.2 release.
> 
> So, thankfuly, it's not a regression bug after all :) In 1.1.4 the image is sticking the same way as it was in 1.1.3. I know, it's bad, but at least it's not worse. In 1.2 it's fixed.
> 
> But since I've found one another issue causing tests to fail before they even start, I should maybe release yet another quick patch patch version, which might have this issue's fix included.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/pisi/Reel/issues/46#issuecomment-4221616

Hi Pisi,

thanks for the fast reply!

Another issue still there, not
a big deal I can rename by myself,
but for others it would be better,
if issue #51 would be fixed:
could you please rename slide to something like reelslide,
slidexy or something else? I would not use pan because
that could conflict with some other frameworks.

Have a nice evening,
Oliver

**Comment by otpfiste** [comment] 2012-03-29 09:01
On 28.02.2012 19:06, Petr Vostřel wrote:

> Again, dummy me... I just realized, that this issue's fix is part of the development branch and is slated as far as the 1.2 release.
> 
> So, thankfuly, it's not a regression bug after all :) In 1.1.4 the image is sticking the same way as it was in 1.1.3. I know, it's bad, but at least it's not worse. In 1.2 it's fixed.
> 
> But since I've found one another issue causing tests to fail before they even start, I should maybe release yet another quick patch patch version, which might have this issue's fix included.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/pisi/Reel/issues/46#issuecomment-4221616

Hi Pisi,

just downloaded Version: 1.1.4-devel (Updated: 2012-03-20),
issue 46 is fixed, thanks, but timeout seems not to work anymore,
I set it to 4 sec, but it doesn't stop, quite annoying, see:
http://www.rudolfbrugger.com/en/lavorazioni.html

Regards,
Oliver

**Comment by pisi** [comment] 2012-03-29 12:42
OK, thanks for the feedback. Am looking into it.

**Comment by pisi** [comment] 2012-03-29 15:20
I think I nailed it and since it is a different issue from this, I started a new ticket #111 for you.

**Closed as completed by pisi** 2012-03-29 15:20 UTC
Labels: bug, resolved, verified

**Comment by otpfiste** [comment] 2012-03-29 19:39
On 29.03.2012 17:20, Petr Vostřel wrote:

> I think I nailed it and since it is a different issue from this, I started a new ticket #111 for you.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/pisi/Reel/issues/46#issuecomment-4823361

Hi Pisi,

cool it works well with your new 1.2rc:
http://www.rudolfbrugger.com/it/lavorazioni.html

Thanks a lot,
Oliver
